# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-release
sudo: false
cache: packages
env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes"

after_success:
    - Rscript -e 'covr::codecov()'
