# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-release
sudo: false
cache: packages
warnings_are_errors: false
r_build_args: --no-build-vignettes
r_check_args: --no-build-vignettes

install:
- R -e 'install.packages("devtools")'
- R -e 'devtools::install_deps(dep = T)'

script:
- R CMD build . --no-build-vignettes

after_success:
    - Rscript -e 'covr::codecov()'
